/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


module.exports = [
     {iso_cc: 'IND', c: 'Virat Kholi',year :2019 },
     {iso_cc: 'AFG', c: 'Gulbadin Naib',year :2019},
     {iso_cc: 'AUS', c: 'Aaron Finch',year :2019},
     {iso_cc: 'BNG', c: 'Mashrafe Mortaza',year :2019},
     {iso_cc: 'ENG', c: 'Eoin Morgan',year :2019},
     {iso_cc: 'NZL', c: 'Kane Williamson',year :2019},
     {iso_cc: 'PAK', c: 'Sarfaraz Ahmed',year :2019},
     {iso_cc: 'ZAF', c: 'Faf du Plessis',year :2019},
     {iso_cc: 'LKA', c: 'Dimuth Karunaratne',year :2019},
     {iso_cc: 'WIND', c: 'Jason Holder',year :2019},
     
     {iso_cc: 'IND', c: 'Mahendra Singh Dhoni',year :2015 },
     {iso_cc: 'AFG', c: 'Mohammad Nabi',year :2015},
     {iso_cc: 'AUS', c: 'Michael Clarke',year :2015},
     {iso_cc: 'BNG', c: 'Mashrafe Mortaza',year :2015},
     {iso_cc: 'ENG', c: 'Eoin Morgan',year :2015},
     {iso_cc: 'NZL', c: 'Brendon McCullum',year :2015},
     {iso_cc: 'PAK', c: 'Misbah-ul-Haq Niazi',year :2015},
     {iso_cc: 'ZAF', c: 'AB de Villiers',year :2015},
     {iso_cc: 'LKA', c: 'Angelo Mathews',year :2015},
     {iso_cc: 'WIND', c: 'Jason Holder',year :2015}, 
     {iso_cc: 'KEN', c: 'Jimmy Kamande',year :2015},
     {iso_cc: 'NLD', c: 'Peter Borren',year :2015},
     {iso_cc: 'IRL', c: 'William Porterfield',year :2015},
     {iso_cc: 'ZWE', c: 'Elton Chigumbura',year :2015},
     {iso_cc: 'UAE', c: 'Mohammad Tauqir',year :2015},
     {iso_cc: 'GBR', c: 'Preston Mommsen',year :2015},
     
     {iso_cc: 'IND', c: 'Mahendra Singh Dhoni',year :2011 },
     {iso_cc: 'AFG', c: 'Gulbadin Naib',year :2011},
     {iso_cc: 'AUS', c: 'Ricky Ponting',year :2011},
     {iso_cc: 'BNG', c: 'Shakib Al Hasan',year :2011},
     {iso_cc: 'ENG', c: 'Andrew Straus',year :2011},
     {iso_cc: 'NZL', c: 'Daniel Vettori',year :2011},
     {iso_cc: 'PAK', c: 'Shahid Afridi',year :2011},
     {iso_cc: 'ZAF', c: 'Graeme Smith',year :2011},
     {iso_cc: 'LKA', c: 'Kumar Sangakkara',year :2011},
     {iso_cc: 'WIND', c: 'Darren Sammy',year :2011},
     {iso_cc: 'KEN', c: 'Jimmy Kamande',year :2011},
     {iso_cc: 'NLD', c: 'Peter Borren',year :2011},
     {iso_cc: 'IRL', c: 'William Porterfield',year :2011},
     {iso_cc: 'ZWE', c: 'Elton Chigumbura',year :2011},
     {iso_cc: 'CAN', c: 'Ashish Bagai',year :2011},
     {iso_cc: 'GBR', c: 'Craig Wright',year :2011},
     
     {iso_cc: 'IND', c: 'Rahul Dravid',year :2007 },
     {iso_cc: 'AFG', c: 'Gulbadin Naib',year :2007},
     {iso_cc: 'AUS', c: 'Ricky Ponting',year :2007},
     {iso_cc: 'BNG', c: 'Habibul Bashar',year :2007},
     {iso_cc: 'ENG', c: 'Michael Vaughan',year :2007},
     {iso_cc: 'NZL', c: 'Stephen Fleming',year :2007},
     {iso_cc: 'PAK', c: 'Inzamam-ul-Haq',year :2007},
     {iso_cc: 'ZAF', c: 'Graeme Smith',year :2007},
     {iso_cc: 'LKA', c: 'Mahela Jayawardene',year :2007},
     {iso_cc: 'WIND', c: 'Brian Lara',year :2007},
     {iso_cc: 'KEN', c: 'Steve Tikolo',year :2007},
     {iso_cc: 'NLD', c: 'Luuk van Troost',year :2007},
     {iso_cc: 'IRL', c: 'Trent Johnston',year :2007},
     {iso_cc: 'ZWE', c: 'Prosper Utseya',year :2007},
     {iso_cc: 'CAN', c: 'John Davison',year :2007},
     {iso_cc: 'GBR', c: 'Craig Wright',year :2007},
     {iso_cc: 'BMU', c: 'Irving Romaine',year :2007},
     
     {iso_cc: 'IND', c: 'Sourav Ganguly',year :2003 },
     {iso_cc: 'AFG', c: 'N/A',year :2003},
     {iso_cc: 'AUS', c: 'Ricky Ponting',year :2003},
     {iso_cc: 'BNG', c: 'Khaled Mashud',year :2003},
     {iso_cc: 'ENG', c: 'Nasser Hussain',year :2003},
     {iso_cc: 'NZL', c: 'Stephen Fleming',year :2003},
     {iso_cc: 'PAK', c: 'Waqar Younis',year :2003},
     {iso_cc: 'ZAF', c: 'Shaun Pollock',year :2003},
     {iso_cc: 'LKA', c: 'Sanath Jayasuriya',year :2003},
     {iso_cc: 'WIND', c: 'Carl Hooper',year :2003},
     {iso_cc: 'KEN', c: 'Steve Tikolo',year :2003},
     {iso_cc: 'NLD', c: 'Roland Lefebvre',year :2003},
     {iso_cc: 'NAD', c: 'Deon Kotze',year :2003},
     {iso_cc: 'ZWE', c: 'Heath Streak ',year :2003},
     {iso_cc: 'CAN', c: 'Joe Harris',year :2003},
     
     {iso_cc: 'IND', c: 'Mohammad Azharuddin',year :1999 },
     {iso_cc: 'AFG', c: 'N/A',year :1999},
     {iso_cc: 'AUS', c: 'Steve Waugh',year :1999},
     {iso_cc: 'BNG', c: 'Aminul Islam',year :1999},
     {iso_cc: 'ENG', c: 'Alec Stewart',year :1999},
     {iso_cc: 'NZL', c: 'Stephen Fleming',year :1999},
     {iso_cc: 'PAK', c: 'Wasim Akram',year :1999},
     {iso_cc: 'ZAF', c: 'Gary Kirsten',year :1999},
     {iso_cc: 'LKA', c: 'Arjuna Ranatunga',year :1999},
     {iso_cc: 'WIND', c: 'Brian Lara',year :1999},
     {iso_cc: 'KEN', c: 'Aasif Karim',year :1999},
     {iso_cc: 'ZWE', c: 'Alistair Campbell',year :1999},
     {iso_cc: 'GBR', c: 'George Salmond',year :1999},
      
     {iso_cc: 'IND', c: 'Mohammad Azharuddin',year :1996 },
     {iso_cc: 'AFG', c: 'N/A',year :1996},
     {iso_cc: 'AUS', c: 'Mark Taylor',year :1996},
     {iso_cc: 'BNG', c: 'N/A',year :1996},
     {iso_cc: 'ENG', c: 'Michael Atherton',year :1996},
     {iso_cc: 'NZL', c: 'Lee Germon',year :1996},
     {iso_cc: 'PAK', c: 'Wasim Akram',year :1996},
     {iso_cc: 'ZAF', c: 'Hansie Cronje',year :1996},
     {iso_cc: 'LKA', c: 'Arjuna Ranatunga',year :1996},
     {iso_cc: 'WIND', c: 'Richie Richardson',year :1996},
     {iso_cc: 'KEN', c: 'JMaurice Odumbe',year :1996},
     {iso_cc: 'NLD', c: 'Steven Lubbers',year :1996},
     {iso_cc: 'UAE', c: 'Sultan Zarawani',year :1996},
     {iso_cc: 'ZWE', c: 'Andy Flower',year :1996},
     
     {iso_cc: 'IND', c: 'Mohammad Azharuddin',year :1992 },
     {iso_cc: 'AFG', c: 'N/A',year :1992},
     {iso_cc: 'AUS', c: 'Allan Border',year :1992},
     {iso_cc: 'BNG', c: 'N/A',year :1992},
     {iso_cc: 'ENG', c: 'Graham Gooch',year :1992},
     {iso_cc: 'NZL', c: 'Martin Crowe',year :1992},
     {iso_cc: 'PAK', c: 'Imran Khan',year :1992},
     {iso_cc: 'ZAF', c: 'Kepler Wessels',year :1992},
     {iso_cc: 'LKA', c: 'Aravinda de Silva',year :1992},
     {iso_cc: 'WIND', c: 'Richie Richardson',year :1992},
     {iso_cc: 'ZWE', c: 'David Houghton',year :1992},
     
     {iso_cc: 'IND', c: 'Kapil Dev',year :1987 },
     {iso_cc: 'AFG', c: 'N/A',year :1987},
     {iso_cc: 'AUS', c: 'Allan Border',year :1987},
     {iso_cc: 'BNG', c: 'N/A',year :1987},
     {iso_cc: 'ENG', c: 'Mike Gatting',year :1987},
     {iso_cc: 'NZL', c: 'Jeff Crowe',year :1987},
     {iso_cc: 'PAK', c: 'Imran Khan',year :1987},
     {iso_cc: 'ZAF', c: 'N/A',year :1987},
     {iso_cc: 'LKA', c: 'Duleep Mendis',year :1987},
     {iso_cc: 'WIND', c: 'Viv Richards',year :1987},
     {iso_cc: 'ZWE', c: 'John Traicos',year :1983},
     
     {iso_cc: 'IND', c: 'Kapil Dev',year :1983 },
     {iso_cc: 'AFG', c: 'N/A',year :1983},
     {iso_cc: 'AUS', c: 'Kim Hughes',year :1983},
     {iso_cc: 'BNG', c: 'N/A',year :1983},
     {iso_cc: 'ENG', c: 'Bob Willis',year :1983},
     {iso_cc: 'NZL', c: 'Geoff Howarth',year :1983},
     {iso_cc: 'PAK', c: 'Imran Khan',year :1983},
     {iso_cc: 'ZAF', c: 'N/A',year :1983},
     {iso_cc: 'LKA', c: 'Duleep Mendis',year :1983},
     {iso_cc: 'WIND', c: 'Clive Lloyd',year :1983},
     {iso_cc: 'ZWE', c: 'Duncan Fletcher',year :1983},
     
      {iso_cc: 'IND', c: 'Srinivas Venkataraghavan',year :1979 },
     {iso_cc: 'AFG', c: 'N/A',year :1979},
     {iso_cc: 'AUS', c: 'Kim Hughes',year :1979},
     {iso_cc: 'BNG', c: 'N/A',year :1979},
     {iso_cc: 'ENG', c: 'Mike Brearley',year :1979},
     {iso_cc: 'NZL', c: 'Mark Burgess',year :1979},
     {iso_cc: 'PAK', c: 'Asif Iqbal',year :1979},
     {iso_cc: 'ZAF', c: 'N/A',year :1979},
     {iso_cc: 'LKA', c: 'Anura Tennekoon',year :1979},
     {iso_cc: 'WIND', c: 'Clive Lloyd',year :1979},
     {iso_cc: 'CAN', c: 'Bryan Mauricette',year :1979},
     
     
     {iso_cc: 'IND', c: 'Srinivasaraghavan Venkataraghavan',year :1975},
     {iso_cc: 'AFG', c: 'N/A',year :1975},
     {iso_cc: 'AUS', c: 'Ian Chappell',year :1975},
     {iso_cc: 'BNG', c: 'N/A',year :1975},
     {iso_cc: 'ENG', c: 'Mike Denness',year :1975},
     {iso_cc: 'NZL', c: 'Glenn Turner',year :1975},
     {iso_cc: 'PAK', c: 'Asif Iqbal',year :1975},
     {iso_cc: 'ZAF', c: 'Harilal Shah',year :1975},
     {iso_cc: 'LKA', c: 'Anura Tennekoon',year :1975},
     {iso_cc: 'WIND', c: 'Clive Lloyd',year :1975} ,
];
